#https://jekyllrb.com/docs/continuous-integration/travis-ci/
#https://gist.github.com/willprice/e07efd73fb7f13f917ea
language: ruby
rvm:
- 2.4.1
script: "jgd -b master -r dev -u https://${GH_TOKEN}@github.com/Finesim97/finesim97.github.io.git"
branches:
  only:
  - dev
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: fTeRR3tOjLqqwg6QZDOjTTJvl9zLFv3V18f9wijPaDGPVUmPnJXGFQFZQUyA8OKlQWXkLoN6iIdtCo2w8aCBbgfjDpF05+AcnIE+HHY6t+mBwPGw2EJ5240WwfJBKwEkOwnJaZPlvHndxrXPeKquxJA4oorgeYJEA9sYH/voC5rU5Inl2ARWbM7+LY806EK3EzqbMlpxCs+k+2MKL6OvAydWbEFYCUtnqEHoLMzUZy7mWvx2tE1jb8kR+WYMpyK1ekZq252sgyhjGapJkl/hiBJ/oNf54dplgUqKYt7yb9puRQOE1xy9iWu0reffyH5szMVEJQJ48xgHpwrKIzFl9a15iKpTTzkNkMrTWqK5bA9DlpxzdBTUR4jOs6e7SSIuqWwabBZKEulnWoYF8GOxNCHhyKvx485Pr9bHz/1bxIHonv/8RpoJCpfcLS0laZmMiP1fP+++bSpi8g1tuuq1HhUHcA9tJdX75DsYJek03gx0OSm4oYDgsgEUQI0zVsmsI/i4pd/D1eWOqLQR152kfSOvnWi9VZuuvpIZC08AtbtAiYwRxL5iJajiwtdBb1aeqFx8NTiEgZ2Ln1vmVkecEyfuJHyTj+MUEK0zFRL6Ybhf6m4+mQuaElEKIuNT4vJK5cayo7JOSWg2EkU5awId/AjxG5DpDtjeD50UK8uu1Zc=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
